### ISSUE TITLE
Deprecation warnings coming from latest `ansys.platform.instancemanagement` 

### ISSUE THREAD

**Issue by pkrull-ansys** [ansys/pypim#81]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Deprecation warnings are logged when importing or performing unit tests of code that imports `ansys-platform-instancemanagement` version 1.1.1.

```
.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:21
  C:\AnsysDev\NoBackup\src\pyadditive\.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:21: DeprecationWarning: Call to deprecated create function FileDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    DESCRIPTOR = _descriptor.FileDescriptor(

.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:40
  C:\AnsysDev\NoBackup\src\pyadditive\.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:40: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(

.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:47
  C:\AnsysDev\NoBackup\src\pyadditive\.tox\py\Lib\site-packages\ansys\api\platform\instancemanagement\v1\product_instance_manager_pb2.py:47: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(
```

### 📝 Steps to reproduce

pip install ansys-platform-instancemanagement
python -W default -c 'import ansys.platform.instancemanagement'

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

24.1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
python -m pip freeze
ansys-api-platform-instancemanagement==1.0.0b3
ansys-platform-instancemanagement==1.1.1
googleapis-common-protos==1.59.1
grpcio==1.56.0
importlib-metadata==6.7.0
protobuf==3.20.3
protoc-gen-swagger==0.1.0
zipp==3.15.0
```

**Comment by plule-ansys** [comment]
Thanks @pkrull-ansys, we have an ongoing update to ansys-api-platform-instancemanagement regenerating with a newer `protoc` which I believe will fix this issue - to be confirmed once done

**Comment by plule-ansys** [comment]
> @plule-ansys You may want to look at using https://github.com/ansys/ansys-tools-protoc-helper if you don't already.

Yes, it is now using this tool, we were completing the new release process. I was unable to see the warning myself, but you should not see this warning anymore starting with `ansys-api-platform-instancemanagement` v1.0.0b4 that was released a bit earlier today.

Closing, feel free to reopen if the warning is still happening in v1.0.0b4

**Comment by pkrull-ansys** [comment]
@plule-ansys I'm a little confused. Did the version numbers go backward? I was already using v1.1.1. If I try to install 1.0.0b4 I get 
```
pip install ansys-platform-instancemanagement==1.0.0b4                                                                                   
Looking in indexes: https://pypi.org/simple, https://****@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/
ERROR: Could not find a version that satisfies the requirement ansys-platform-instancemanagement==1.0.0b4 (from versions: 0.1.dev0, 0.1.dev1, 0.1.dev2, 0.1.0, 0.2.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1)
ERROR: No matching distribution found for ansys-platform-instancemanagement==1.0.0b4
```

**Comment by pkrull-ansys** [comment]
@plule-ansys I no longer seeing the warnings after updating `ansys-api-platform-instancemanagement`.
